name: send-css-to-s3

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Set up Ruby 2.7
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.7
      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build static assets
        run: rails webpacker:compile
