name: send-css-to-s3

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build static assets
        run: rails webpacker:compile
